# Generated by Django 2.1.5 on 2019-02-04 01:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemHunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('zipcode', models.CharField(max_length=5)),
                ('radius', models.IntegerField(null=True)),
                ('section', models.CharField(default='free', max_length=80)),
                ('minprice', models.FloatField(default=0.0)),
                ('maxprice', models.FloatField(default=float("inf"))),
                ('listing_age', models.FloatField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordPriorityPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=220)),
                ('priority', models.IntegerField()),
                ('itemhunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watcher.ItemHunt')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(null=True)),
                ('html', models.TextField(null=True)),
                ('location', models.TextField()),
                ('image_urls', models.TextField(default='')),
                ('time_posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('predicted_score', models.FloatField(null=True)),
                ('user_score', models.FloatField(null=True)),
                ('dismissed', models.BooleanField(default=False)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ListingURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('scraped', models.BooleanField(default=False)),
            ],
        ),
    ]
