# Generated by Django 2.1.5 on 2019-01-21 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('url', models.TextField()),
                ('location', models.TextField()),
                ('time_posted', models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 21, 19, 53, 56, 612925))),
            ],
        ),
    ]
