# Generated by Django 2.1.5 on 2019-01-21 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='time_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
