# Generated by Django 2.1.5 on 2019-01-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0002_auto_20190121_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
