# Generated by Django 2.1.5 on 2019-01-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0003_listing_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingURLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.TextField()),
                ('scraped', models.BooleanField(default=False)),
            ],
        ),
    ]
