# Generated by Django 2.1.5 on 2019-01-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0004_listingurls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.TextField(unique=True)),
                ('scraped', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ListingURLs',
        ),
    ]
