# Generated by Django 2.1.5 on 2019-01-22 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0005_auto_20190122_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='html',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listingurl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watcher.ListingURL'),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='predicted_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='user_score',
            field=models.FloatField(null=True),
        ),
    ]
