# Generated by Django 2.1.5 on 2019-01-22 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0006_auto_20190122_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='url',
        ),
    ]
