# Generated by Django 2.1.5 on 2019-02-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0008_itemhunt_keywordprioritypair'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_urls',
            field=models.TextField(default=''),
        ),
    ]
